const mockData = [
    {
        id: 1,
        university: "University of Bath",
        Title: "Selection of Beans",
        User: "John Doe",
        Date: "2025-07-01",
        image: "beans.png",
        price: "£4.00",
        description: "A selection of beans that I have grown in my garden. I have too many and would like to share them with someone who can make use of them.",
    },
    {
        id: 2,
        university: "University of Bath",
        Title: "Cookies!!1",
        User: "John Doe",
        Date: "2025-07-01",
        image: "cookies.jpg",
        price: "£2.00",
        description: "I made too many cookies and I don't want them to go to waste. They are chocolate chip cookies and they are delicious.",
    },
    {
        id: 3,
        university: "University of Bath",
        Title: "Cake that i made and do not like",
        User: "John Doe",
        Date: "2025-07-01",
        image: "cake.jpg",
        price: "£1.00",
        description: "I made a cake and I do not like it. I would like to give it to someone who can make use of it. It is a chocolate cake with vanilla frosting. I am allergic to cake.",
    },
    {
        id: 4,
        university: "University of Bath",
        Title: "Eggs that i need to get rid of",
        User: "John Doe",
        Date: "2025-07-01",
        image: "eggs.jpeg",
        price: "£2.00",
        description: "I have too many eggs and I need to get rid of them. I would like to give them to someone who can make use of them. They are fresh and organic.",
    },
    {
        id: 5,
        university: "University of Bath",
        Title: "HOMEMADE SAMOSASSSSSS",
        User: "John Doe",
        Date: "2025-07-01",
        image: "samosa.jpg",
        price: "£1.50",
        description: "I made too many samosas and I would like to give them to someone who can make use of them. They are delicious and spicy.",
    },
    {
        id: 1,
        university: "University of Bristol",
        Title: "Sourdough Bread loaf",
        User: "John Doe",
        Date: "2025-07-01",
        image: "sourdough.jpg",
        price: "£6.50",
        description: "I made too much sourdough bread and I would like to give it to someone who can make use of it. It is fresh and delicious.",
    },
    {
        id: 2,
        university: "University of Bristol",
        Title: "Fruit smoothies boshhh",
        User: "John Doe",
        Date: "2025-07-01",
        image: "smoothies.jpeg",
        price: "£3.50",
        description: "I made too many fruit smoothies and I would like to give them to someone who can make use of them. They are fresh and delicious.",
    },
    {
        id: 3,
        university: "University of Bristol",
        Title: "Pasta bake",
        User: "John Doe",
        Date: "2025-07-01",
        image: "pasta.jpg",
        price: "£8.00",
        description: "I made too much pasta bake and I would like to give it to someone who can make use of it. It is fresh and delicious.",
    },
    {
        id: 1,
        university: "University of Cambridge",
        Title: "Excess rice :( too much rice",
        User: "John Doe",
        Date: "2025-07-01",
        image: "rice.jpeg",
        price: "£5.00",
        description: "I have too much rice and I would like to give it to someone who can make use of it. It is fresh and delicious.",
    },
    {
        id: 2,
        university: "University of Cambridge",
        Title: "Literally everything in my freezer",
        User: "John Doe",
        Date: "2025-07-01",
        image: "freezer.jpeg",
        price: "£10.00",
        description: "I am going on holiday and I need to get rid of everything in my freezer. I would like to give it to someone who can make use of it. It is all fresh and delicious.",
    },
    {
        id: 1,
        university: "University of Warwick",
        Title: "Bag of apples",
        User: "John Doe",
        Date: "2025-07-01",
        image: "apples.jpg",
        price: "£4.00",
        description: "Selling a bag of apples within date.",
    },
    {
        id: 2,
        university: "University of Warwick",
        Title: "Tins of tuna",
        User: "John Doe",
        Date: "2025-07-01",
        image: "tuna.jpg",
        price: "£2.00",
        description: "Selling tins of tuna. Why? Because I can.",
    },
    {
        id: 3,
        university: "University of Warwick",
        Title: "1 year supply of pot noodles",
        User: "John Doe",
        Date: "2025-07-01",
        image: "potnoodles.jpeg",
        price: "£20.00",
        description: "I have a 1 year supply of pot noodles that I would like to sell. Help me get rid of them please I have too many please.",
    },
];

export default mockData;
